
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Header from './components/header'
import { dark } from '@clerk/themes'
import { Raleway  } from 'next/font/google'
import { useEffect, useState} from 'react'
import { UserLocationContext } from './context/UserLocationContext'

const raleway = Raleway({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) { 


  return (
    <ClerkProvider appearance={dark}>
      <html lang='en'>
        
        <body className={raleway.className}>
          <Header/>
          <main>
            <div>
              <div>{children}</div>
            </div>
          </main>
        </body>
      </html>
      
    </ClerkProvider>

  )
}
